In [1]:
def printm(matrix):
    print('[ ')
    
    for row in matrix:
        print('\t[', end=' ')    
        
        for cell in row:
            print(f'{cell}', end=' ')
        
        print(']')
            
    print(']')

In [2]:
import numpy as np

In [ ]:
# Basics

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
b = np.array([[1, 2, 3], [1, 2, 3]], dtype='int8')
b

array([[1, 2, 3],
       [1, 2, 3]], dtype=int8)

In [5]:
# Get dimension

print(a.ndim)
print(b.ndim)

1
2


In [6]:
# Get shape

print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [7]:
# Get data type

print(a.dtype)
print(b.dtype)

int64
int8


In [8]:
# Get total size in bytes

print(a.nbytes)
print(b.nbytes)

24
6


# Assecing/Changing sepecific elements, row, columns, etc

In [9]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a.shape)

(2, 7)


In [10]:
# Get specific cell: array["row", "column"]

print(a[0, 6])
print(a[1, -3])

7
12


In [11]:
# Get row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get column
a[:, 2]

array([ 3, 10])

In [13]:
# More advanced stuff array["startindex":"endindex":"stepsize"]

a[0, 1:7]

array([2, 3, 4, 5, 6, 7])

In [14]:
a[0, 2:-1:2] # -2 pra pegar o último pq é exclusivo

array([3, 5])

In [15]:
a[1, 5] = 700
printm(a)

[ 
	[ 1 2 3 4 5 6 7 ]
	[ 8 9 10 11 12 700 14 ]
]


In [16]:
# Generate ramdomic numbers

np.random.rand(7,3)

array([[1.39379210e-01, 1.54923793e-01, 2.64347039e-01],
       [7.12463957e-01, 9.87290928e-01, 4.39689400e-01],
       [6.16345241e-01, 7.51555600e-01, 9.79756042e-01],
       [7.18381315e-04, 9.20482536e-01, 1.48135190e-01],
       [3.95485007e-01, 4.03081442e-01, 4.19263070e-01],
       [1.40803913e-01, 6.03101147e-01, 5.02297389e-01],
       [1.51235543e-01, 4.28463450e-02, 7.05568060e-01]])

In [17]:
np.random.randint(10, size=(3, 3))

array([[5, 7, 5],
       [1, 2, 0],
       [9, 7, 6]])

In [18]:
# Identity matrix

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
arr = np.array([7, 8, 9])
arr2 = np.repeat(arr, 3)
print(arr2)

[7 7 7 8 8 8 9 9 9]


In [20]:
arr3 = np.array([[1,2,3]])
arr4 = np.repeat(arr3, 3, axis=0)
print(arr4)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [21]:
arr3 = np.array([[1,2,3]])
arr4 = np.repeat(arr3, 3, axis=1)
print(arr4)

[[1 1 1 2 2 2 3 3 3]]


In [22]:
# Desafiozinho lá

c = np.ones((5, 5), dtype='int32')
c[1:-1, 1:-1] = np.zeros((3, 3), dtype='int32')
c[2, 2] = 9
printm(c)

[ 
	[ 1 1 1 1 1 ]
	[ 1 0 0 0 1 ]
	[ 1 0 9 0 1 ]
	[ 1 0 0 0 1 ]
	[ 1 1 1 1 1 ]
]


In [68]:
data_nparray_linspace = np.linspace(1, 10, 5, dtype='int32')
print(data_nparray_linspace)

[ 1  3  5  7 10]


# Mathematics

In [26]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [29]:
a + 3

array([4, 5, 6, 7])

In [31]:
a * 7

array([ 7, 14, 21, 28])

In [32]:
a - 2

array([-1,  0,  1,  2])

In [33]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [34]:
a ** 9

array([     1,    512,  19683, 262144])

In [35]:
a % 2

array([1, 0, 1, 0])

In [38]:
b = np.array([1, 1, 1, 1])
a + b

array([2, 3, 4, 5])

In [40]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [41]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)


# Linear Algebra

In [43]:
a = np.ones((2, 3))
b = np.full((3, 2), 2)

In [44]:
# Multiplicação de matriz

np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [45]:
# Achar o determinante de uma matriz

c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# Estatítica

In [46]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
print(stats)

[[1 2 3]
 [1 2 3]]


In [47]:
np.min(stats)

1

In [49]:
np.max(stats, axis=1)  # column com a maior soma de valores

array([3, 3])

# Reorganizando Arrays

In [61]:
# Reshape

before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((8,1))
print('\n', after)

after = before.reshape((4,2))
print('\n', after)

after = before.reshape((2, 2, 2))
print('\n', after)

[[1 2 3 4]
 [5 6 7 8]]

 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [62]:
# Vertically stacking vectors

v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
# Horizontally stacking vectors

h1 = np.ones([2, 4], dtype='int32')
h2 = np.zeros([2, 2], dtype='int32')

np.hstack([h1, h2, h1, h2])

array([[1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0]], dtype=int32)

In [ ]:
# Boolean masking and advanced indexing

In [82]:
filedata = np.array([[1, 13, 21, 11, 196, 75, 4, 3, 34, 6, 7, 8, 0, 1, 2, 3, 4, 5],
                     [3, 42, 12, 33, 766, 75, 4, 55, 6, 4, 3, 4, 5, 6, 7, 0, 11, 12],
                     [1, 22, 33, 11, 999, 11, 2, 1, 78, 0, 1, 2, 9, 8, 7, 1, 76, 88]])

In [83]:
filedata > 10

array([[False,  True,  True,  True,  True,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True, False,  True, False,
        False, False, False, False, False, False, False,  True,  True],
       [False,  True,  True,  True,  True,  True, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [85]:
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [ ]:
# np.full(shape, fill_value, dtype=None, order='C', *, like=None)

sevens = np.full()